# Generated by Django 3.1.2 on 2020-10-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('isbn', models.IntegerField(default=0)),
                ('numeroPagina', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=50)),
                ('anoPublicacao', models.IntegerField(default=0)),
                ('emailEditora', models.EmailField(max_length=50)),
            ],
        ),
    ]
