# Generated by Django 3.1.2 on 2020-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20201013_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlTeca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas', models.IntegerField(default=0)),
                ('publicacao', models.IntegerField(default=0)),
                ('assunto', models.IntegerField(default=0)),
                ('avaliacao', models.IntegerField(default=0)),
            ],
        ),
    ]
