# Generated by Django 3.1.2 on 2020-12-30 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_mlteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 11, 39, 15, 852439)),
        ),
    ]
