# Generated by Django 3.1.2 on 2021-01-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_livro_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 15, 40, 42, 37905)),
        ),
    ]
